# Generated by Django 3.2 on 2021-04-19 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('BookID', models.IntegerField()),
                ('User', models.CharField(max_length=50)),
                ('DoI', models.DateField(auto_now_add=True)),
                ('DoD', models.DurationField(default=datetime.timedelta(days=7))),
                ('state', models.CharField(choices=[('Requested', 'Requested'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('NA', 'NA')], default='Requested', max_length=9)),
                ('Comments', models.TextField(null=True)),
            ],
        ),
    ]
