# Generated by Django 3.2 on 2021-04-17 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookissue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='DoR',
        ),
        migrations.AlterField(
            model_name='issue',
            name='DoD',
            field=models.TimeField(default=datetime.datetime(2021, 4, 29, 11, 33, 39, 26804)),
        ),
    ]
