# Generated by Django 3.2 on 2021-04-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookissue', '0002_auto_20210417_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='DoD',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='DoI',
            field=models.DateField(auto_now_add=True),
        ),
    ]
