# Generated by Django 3.2 on 2021-04-17 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookissue', '0003_auto_20210417_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='DoD',
            field=models.TimeField(default=datetime.date(2021, 4, 29)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='DoI',
            field=models.DateField(default=datetime.date(2021, 4, 17)),
        ),
    ]
