# Generated by Django 3.2 on 2021-04-18 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookissue', '0004_auto_20210417_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='DoD',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='DoI',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('NA', 'NA')], default='Requested', max_length=9),
        ),
    ]
