# Generated by Django 3.2 on 2021-04-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Author', models.CharField(max_length=120)),
                ('Publisher', models.CharField(max_length=120)),
                ('Genre', models.CharField(max_length=120)),
                ('ISBN', models.CharField(max_length=13)),
                ('Location', models.TextField()),
                ('Available', models.BooleanField(default=True)),
                ('Comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('BookID', models.IntegerField()),
                ('User', models.CharField(max_length=50)),
                ('DoI', models.DateField()),
                ('DoD', models.DateField()),
                ('State', models.CharField(choices=[('Requested', 'Requested'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('NA', 'NA')], default='Requested', max_length=9)),
                ('Comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('userID', models.CharField(max_length=50)),
                ('bookID', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
