# Generated by Django 3.2 on 2021-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Author', models.CharField(max_length=120)),
                ('Publisher', models.CharField(max_length=120)),
                ('Genre', models.CharField(max_length=120)),
                ('ISBN', models.CharField(max_length=13)),
                ('Available', models.BooleanField(default=True)),
            ],
        ),
    ]
