# Generated by Django 3.2 on 2021-04-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Location',
            field=models.TextField(default='Shelf'),
            preserve_default=False,
        ),
    ]
