# Generated by Django 3.2 on 2021-04-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_issue_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='bookID',
            field=models.CharField(max_length=50),
        ),
    ]
