# Generated by Django 3.2 on 2021-04-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Comments',
            field=models.TextField(null=True),
        ),
    ]
