# Generated by Django 3.2 on 2021-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('BookID', models.IntegerField()),
                ('User', models.CharField(max_length=50)),
                ('DoI', models.TimeField(auto_now_add=True)),
                ('DoD', models.TimeField()),
                ('DoR', models.TimeField()),
                ('state', models.CharField(choices=[('Requested', 'Requested'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('NA', 'NA')], default='Requested', max_length=50)),
                ('Comments', models.TextField(null=True)),
            ],
        ),
    ]
