# Generated by Django 3.2 on 2021-04-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_rate_bookid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Rating',
        ),
    ]
