# Generated by Django 3.2 on 2021-04-18 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='DoR',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='state',
        ),
        migrations.AddField(
            model_name='issue',
            name='State',
            field=models.CharField(choices=[('Req', 'Requested'), ('Is', 'Issued'), ('Ret', 'Returned'), ('N', 'NA')], default='Req', max_length=9),
        ),
        migrations.AlterField(
            model_name='issue',
            name='DoD',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='DoI',
            field=models.DateField(auto_now_add=True),
        ),
    ]
