# Generated by Django 3.2 on 2021-04-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_rate_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rates', models.IntegerField()),
                ('userID', models.CharField(max_length=50)),
                ('bookID', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
    ]
