# Generated by Django 3.2 on 2021-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='usrrnme',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
