# Generated by Django 3.2 on 2021-04-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rates_usrrnme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AlterField(
            model_name='issue',
            name='State',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Issued', 'Issued'), ('Returned', 'Returned'), ('Request Extension', 'Request Extension'), ('Extended Issue', 'Extended Issue'), ('Issued/Ext Denied', 'Issued/Ext Denied'), ('Rejected Issue', 'Rejected Issue'), ('NA', 'NA')], default='Requested', max_length=50),
        ),
    ]
