# Generated by Django 3.2 on 2021-04-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210422_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Lost',
            field=models.BooleanField(default=False),
        ),
    ]
