# Generated by Django 3.2 on 2021-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='SoftCopy',
            field=models.URLField(blank=True),
        ),
    ]
